server:
  servlet:
    context-path: /vuce-zee-api-tesoreria
  port : 8081
spring:
  datasource:
    url: jdbc:postgresql://10.19.34.188:5432/zee_db?currentSchema=vuce_zee
    username: zeeperu
    password: CicQB888PD8LJGxn
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        # Hibernate ddl auto (create, create-drop, validate, update, none)
        ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
identidad:
  consultaDniUrl: 'http://10.19.34.157:30000/'
  consultaRucUrl: 'http://endose-sunat-api-service.development.svc.cluster.local'