server:
  servlet:
    context-path: /vuce-zee-api-maestros
  port : 8081
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        # Hibernate ddl auto (create, create-drop, validate, update, none)
        ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
